"""nodes table

Revision ID: 40677feba294
Revises: 
Create Date: 2019-03-14 21:14:37.510640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40677feba294'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('transform', postgresql.ARRAY(FLOAT()), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_image'), 'nodes', ['image'], unique=True)
    op.create_index(op.f('ix_nodes_subtitle'), 'nodes', ['subtitle'], unique=True)
    op.create_index(op.f('ix_nodes_title'), 'nodes', ['title'], unique=True)
    op.create_index(op.f('ix_nodes_type'), 'nodes', ['type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_type'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_title'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_subtitle'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_image'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
